FROM python:3.10.13-slim

WORKDIR /src

COPY dags/training /src/training
COPY dags/constants /src/constants
COPY dags/utils /src/utils

RUN pip install tensorflow minio

CMD ["python", "/src/training/model_training.py"]
