FROM --platform=$TARGETPLATFORM python:3.10.13-slim

WORKDIR /src

COPY dags/evaluate /src/evaluate
COPY dags/constants /src/constants
COPY dags/utils /src/utils

RUN pip install tensorflow minio

CMD ["python", "/src/evaluate/model_evaluate.py"]
