FROM python:3.10.13-slim

WORKDIR /src

COPY dags/preprocess /src/preprocess
COPY dags/constants /src/constants
COPY dags/utils /src/utils

RUN pip install tensorflow minio

CMD ["python", "/src/preprocess/data_preprocess.py"]
